### ISSUE TITLE
Cannot install v~1.1 on Laravel 5.1.26 using composer

### ISSUE THREAD

**Issue by omarjebari** [vinicius73/laravel-model-shield#2]
I'm running Laravel v5.1.26.
I thought this package was supposed to support Laravel 5+ but I'm getting the following error when i try to install ("vinicius73/laravel-model-shield": "~1.1") using composer update:
- vinicius73/laravel-model-shield v1.1 requires illuminate/support 4.*

**Comment by vinicius73** [comment]
There are currently no support for Laravel 5+

**Comment by omarjebari** [comment]
Please change the title on Packagist because it says:
'Validation package for models Laravel 5+'
This implies that it has Laravel 5+ support.
See https://packagist.org/packages/vinicius73/laravel-model-shield

**Comment by vinicius73** [comment]
Sorry about that.
The L5 compatibility is still undeveloped.

Packagist uses the master branch information.
I'll see what I can do.
